# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: radoscis/pipelines-templates
      ref: refs/heads/master
      endpoint: radoscis

pool:
    vmImage: 'ubuntu-latest'
variables:
- group: GitHub
- group: DEFAULT_PROJECT_SETTINGS

stages:
- stage: 'Build'
  jobs:
  - template: gradle_java/gradle.yml@templates
    parameters:
      workingDirectory: ''
      gitCiToken: "$(GH_TOKEN)"
      gitCiUserMail: "$(GH_USER_MAIL)"
      gitCiUserName: "$(GH_USER_NAME)"
- template: gradle_java/store_blob.yml@templates
  parameters:
    azSubRmConnection: "$(AZ_RM_CONNECTION)"
    azContainerRegistryName: "$(AZ_CONTAINER_REGISTRY_NAME)"